[package]
name = "InitialGUI"
version = "0.1.0"
authors = ["lminozzo <laerciominozzo@hotmail.com>"]
edition = "2018"

[dependencies]
gtk = "^0"
gdk = "^0"
gdk-pixbuf = "^0"
rand = "0.7.0-pre.1"


[features]
gtk_3_10 = ["gtk/v3_10"]


